from .free_consultation_page import FreeConsultationPage
from .login_page import LoginPage
from .my_account_page import MyAccountPage
from .main_page import MainPage
from .registration_page import RegistrationPage
from .services_page import ServicesPage
from .guides_page import GuidesPage
from .cart_page import CartPage
from .checkout_page import CheckoutPage
from .complete_purchase_page import CompletePurchasePage
