Feature: Free Consultation

  Scenario Outline: Submit free consultation form

    Given I am on Free Consultation page
    When I fill part of Contact information with <f_name>, <l_name>, <email>, <phone>, <password>, <repeat_pass>
    And I fill another part of Contact information with <hear_how>, <cons_name>, <subscr>, <programs>, <month>, <year>
    And I fill Academic Information with <instit>, <gpa>, <major>, <YoG>
    And I choose <gmat_gre> of GMAT/GRE
    And I fill Resume Upload with <resume>, <comments>
    And I fill Post-MBA Career Goals with <goals>
    And I fill captcha with <captcha>
    And I click Submit Form button
    Then I want to get result - <result>
    And as administrator I want to receive <emails_number> new emails
    And I want to see Free Consultation data in email if email received

    Examples:
      | f_name | l_name | email          | phone | password   | repeat_pass | hear_how | cons_name | subscr | programs              | month | year  | instit | gpa   | major | YoG   | gmat_gre | resume    | comments | goals | captcha | result                                                                                              | emails_number |
      | A      | B      | <unique_email> | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see success message                                                                       | 1             |
      | empty  | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "First Name cannot be blank."                                           | 0             |
      | A      | empty  | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Last Name cannot be blank."                                            | 0             |
      | A      | B      | empty          | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Email cannot be blank."                                                | 0             |
      | A      | B      | abc            | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Email is not a valid email address."                                   | 0             |
      | A      | B      | abc@bca        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Email is not a valid email address."                                   | 0             |
      | A      | B      | a@b.cde        | empty | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Phone cannot be blank."                                                | 0             |
##      | A      | B      | <unique_email> | abcde | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty |testme       | I want to see error message "Is not phone number."                                                  | 0             |
      | A      | B      | a@b.cde        | 12345 | empty      | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Password cannot be blank."                                             | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | empty       | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Re-type password cannot be blank."                                     | 0             |
      | A      | B      | a@b.cde        | 12345 | 123        | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Password should contain at least 6 characters."                        | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 123         | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Re-type password should contain at least 6 characters."                | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 1234567     | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Should be the same as Password"                                        | 0             |
      | A      | B      | a@b.cde        | 12345 | <spaces:6> | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Password cannot be blank."                                             | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | <spaces:6>  | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Re-type password cannot be blank."                                     | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | empty    | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Influence cannot be blank."                                            | 0             |
#      | A      | B      | <unique_email> | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.docx | empty    | empty | testme  | I want to see success message                                                                       | 1             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | empty  | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Subscribe cannot be blank."                                            | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['empty','123']       | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Programs cannot be blank."                                             | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | empty | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Month cannot be blank."                                                | 0             |
##      | A      | B      | <unique_email> | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']         | 13    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Incorrect date"                                                        | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | empty | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Year cannot be blank."                                                 | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 05    | 2015  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Incorrect date"                                                        | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | empty  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Undergraduate Institution cannot be blank."                            | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | empty | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "GPA cannot be blank."                                                  | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | empty | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Major cannot be blank."                                                | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | empty | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "Year of Graduation cannot be blank."                                   | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | empty     | empty    | empty | testme  | I want to see error message "Only files with these extensions are allowed: pdf, doc,and the docx."  | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | bad.pdf   | empty    | empty | testme  | I want to see error message "Only files with these extensions are allowed: pdf, doc,and the docx."  | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | large.pdf | empty    | empty | testme  | I want to see error message "The file "large.pdf" is too big. Its size cannot exceed 512000 bytes." | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | file.png  | empty    | empty | testme  | I want to see error message "Only files with these extensions are allowed: pdf, doc,and the docx."  | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | metest  | I want to see error message "The verification code is incorrect."                                   | 0             |
      | A      | B      | a@b.cde        | 12345 | 12345678   | 12345678    | Facebook | John Sisk | No     | ['123']               | 12    | 2016  | abcde  | 1     | 2     | 2016  | gmat     | good.pdf  | empty    | empty | testme  | I want to see error message "User already has requested free consultation"                          | 0             |
#      | A      | B      | <unique_email> | 12345 | 12345678   | 12345678    | Facebook | empty     | Yes    | ['1','2','3','4','5'] | 12    | 2016  | abcde  | 1     | 2     | 2016  | Neither  | good.doc  | 124124   | 41324 | testme  | I want to see success message                                                                       | 1             |